export const baseStyles = {
  metaEditor: {
    width: '70%',
    height: 0,
    overflow: 'hidden',
    backgroundColor: '#fff',
    boxShadow: 'none',
    opacity: 0,
    position: 'absolute',
    top: 0,
    left: -16,
    border: 0,
    zIndex: 0,
  },
  metaEditorShown: {
    height: 'auto',
    overflow: 'visible',
    border: '1px solid #DBDBDB',
    boxShadow: '0 2px 12px rgba(0, 0, 0, 0.12)',
    opacity: 1,
    transition: 'opacity 0.2s ease-out',
    position: 'absolute',
    top: 0,
    left: -16,
    zIndex: 10,
    borderRadius: 4,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexDirection: 'column',
    padding: '0 12px 12px 12px',
  },
};

export const metaStyles = {
  metaModalTitle: {
    width: '100%',
    fontSize: 12,
    lineHeight: '32px',
    color: '#4a4a4a',
    letterSpacing: 1,
    padding: '2px 0 0 1px',
    margin: '0 0 12px 0',
    borderBottom: '1px solid #dfdfdf',
  },
  metaModalTextarea: {
    width: '100%',
    minHeight: '3em',
    border: 0,
    borderRadius: 4,
    fontSize: 15,
    color: '#4a4a4a',
    outline: 'none',
    padding: '0.5em 0.6em',
    resize: 'none',
    backgroundColor: '#f3f3f3',
  },
  metaModalInput: {
    width: '100%',
    height: 30,
    border: 0,
    padding: '0 0.6em',
    fontSize: 15,
    lineHeight: '30px',
    color: '#4a4a4a',
    outline: 'none',
    resize: 'none',
    borderRadius: 4,
    backgroundColor: '#f3f3f3',
  },
  linkTargetButton: {
    position: 'absolute',
    top: 10,
    left: 48,
    padding: 0,
    outline: 'none',
    cursor: 'pointer',
    border: 0,
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    color: '#4a4a4a',
    fontSize: 10,
    letterSpacing: 1,
  },
  checkboxWrapper: {
    width: 12,
    height: 12,
    borderRadius: 6,
    border: '1px solid #dfdfdf',
    padding: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 6px 0 0',
  },
  checkboxChecked: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#1BDCDC',
  },
  removeBtn: {
    width: 14,
    height: 14,
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: '#BD0017',
    borderRadius: 7,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 0,
    padding: 0,
    outline: 'none',
    cursor: 'pointer',
  },
  removeBtnLine1: {
    backgroundColor: '#fff',
    width: 8,
    height: 1,
    transform: 'rotate(45deg)',
    position: 'absolute',
  },
  removeBtnLine2: {
    backgroundColor: '#fff',
    width: 8,
    height: 1,
    transform: 'rotate(135deg)',
    position: 'absolute',
  },
};
